apiVersion: v1
kind: PersistentVolume
metadata:
  name: host-pv
spec:
  hostPath:
    path: /data
    type: DirectoryOrCreate
  capacity:
    storage: 100Mi
  volumeMode: Filesystem
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  